server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laxf_hotel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#集成swagger 遇到error ：Failed to start bean 'documentationPluginsBootstrapper';。添加下一行解决
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    jedis:
      pool:
        min-idle: 5
        max-idle: 10
        max-wait: -1 #默认值： -1ms ，默认无限期等待。含义：建立连接的最长的等待时间。使用负值无限期等待。




mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path: D:\Code\JAVA项目\2022VUE\files\