server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laxf_hotel?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#集成swagger 遇到error ：Failed to start bean 'documentationPluginsBootstrapper';。添加下一行解决
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
files:
  upload:
    path: D:\Code\JAVA项目\2022VUE\files\